// <auto-generated />
using System;
using DbAdapter;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DbAdapter.Migrations
{
    [DbContext(typeof(CriptomoedaDbContext))]
    [Migration("20240107153418_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.25")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Domain.Models.HistoricoNegociacao", b =>
                {
                    b.Property<string>("SiglaMoeda")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaiorPreco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaiorPrecoOfertado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MenorPreco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MenorPrecoOfertado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantidadeNegociada")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("SiglaMoeda");

                    b.ToTable("HistoricoNegociacao");
                });

            modelBuilder.Entity("Domain.Models.HistoricoNegociacoes", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DataHora")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MaiorPreco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MaiorPrecoOfertado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MenorPreco")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("MenorPrecoOfertado")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("PrecoUnitario")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("QuantidadeNegociada")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SiglaMoeda")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HistoricoNegociacoes");
                });
#pragma warning restore 612, 618
        }
    }
}
